{% set version = "0.1.21" %}
{% set name = "PyScreeze" %}

package:
  name: pyscreeze
  version: {{ version }}

source:
  fn: PyScreeze-{{ version }}.tar.gz
  sha256: e798b618acf6836ef5479c2665322d096dfd786b2a38c516a531daa5dfc09915
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - setuptools
    - pip
  run:
    - python
    - pillow

test:
  imports:
    - pyscreeze

about:
  home: https://github.com/asweigart/pyscreeze
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: A simple, cross-platform screenshot module for Python 2 and 3.

extra:
  recipe-maintainers:
    - jschueller
