travis:
  secure:
    BINSTAR_TOKEN: MWjzx0isCOcPSixN1SURqDpZnQbQ5DwBm3WcsCQiQemvub/4R12JSfNj5maoCWLoaVCDYD9L+XhBCby3r1rC4+Wp4svuGNjPiG7ETelKltCcnWh274EiDfXxtPagJ1ljHr8WJT7Zg9etT7nC8/uKFKo3w1tYNWG2Kadlpfy2s17S0iC4bcOsTkniHIIdT1gjW3iyxHHBKrOPd8TBZxU958RjThdhSr5M/JZUQxGjbuZLliFdYTvNpfcB7Kqh661UbBygJrCAnLf6OfO0m1d0g5/3oWnosLkFQLVSbY37zU88HHCxeNJzEO8Kl/MxQIRypFKhm3D/eQicV/70Epw0/EQHKTNZBlSwEK3qiWsd7sV7pWnZIvnK8He11TokdOrM9kbAlzJNmGhXhZoYGfr1w2e/sX2fgMZb8vBfPREo50cWLs0uckHwx8gqmiXftTcnIXYSuXvHTRRjcL+dk56IuzIdc1RZkV+vNfk2o2M5dVDAcqeCE6YtAecGF66mngRYWa0OPh+tGShEpD9WH2UaOQjBiRwT35gk+kDwdbre0gA27y7byX1ximxbwOY5nBwwjJ0hiozzNjtBWCT67qC6ZtP1ShnYWXvw6PTgawC0pnd+07H2IoJPFynswi/1M+ws77cNJ88GL9VCytSMP8agZsrlp6ZGfUpJ/p2F4d10doE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
