travis:
  secure:
    BINSTAR_TOKEN: bghR/QUcFRHnrnMlWVrVwh9hYZcy/BAB1p3PdPHtTD1/Tq4IRO72Gi81z7hvzhSRONjMtGhNBrm2wvQgNH9nH1cFV0RVGGpWmjEP9QlAfjJInKN7oyCeTHnpBPHd6hSihb2nM5e39iTvhrdisVKlHW5OKGqUUP/jnezj5/n8MYfKRd49HrO3kXkp7klWQag+InWxwjpL1Ao7z+f6/mq2HGSqhtWGm/qft3NGBuaW2N7H3RSHdT/hE6TajrLmrppYn1thuovpQOSMg02+g1vr877fT4F7hqAKdgGPoyKjnPEIly+Dhxn/s9X1fWzE19buJD0BimnTkqsSBbXc9Om3fXWdpyPxmQcDBL0QGHygmpGnwbxBlctZCWoiZ4UOHUrSQj1RTzTTIdNEnW5i2Hr02ykcplBhwQv56i4NibaDNhsSEOCnrnkZnESJsmJ4xbIxWnfjQhpkA76ti2+smDz5jDJ/ZuJs90lH60C9mfUITYNxZDo9Tqo0KBXevkj8R23V7G65Rf0LLsMZe2SyS4PylZ8shUzDUoTCHFEsDmjqR0y1Du6JS1QH4y7kn/DfESplGF/s8o1N0bbr6YW2iGjuag7rm4yft0pdExRGX9tq3mr9isrCJSy3khQeFF0wB9WH/dG1RvQqsbvQvFe9LcdEe5Qb6AzYSsklFl5wfyo5wUw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
